### ISSUE TITLE
CMake 3.15 or higher is required.  You are running version 3.10.2

### ISSUE THREAD

**Issue by k1ycee** [mix1009/desktop_window#12]
I keep getting this error, but I have 3.16.2 but it keeps throwing me this build error.

[ +123 ms] executing: [/home/wildone/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +81 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b1395592de68cc8ac4522094ae59956dd21a91db
[   +1 ms] executing: [/home/wildone/snap/flutter/common/flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[  +20 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] 2.0.4
[  +86 ms] executing: [/home/wildone/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/wildone/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +99 ms] executing: [/home/wildone/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +124 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +148 ms] executing: /home/wildone/Android/Sdk/platform-tools/adb devices -l
[  +29 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +140 ms] executing: /home/wildone/Android/Sdk/platform-tools/adb devices -l
[  +25 ms] Skipping pub get: version match.
[  +30 ms] Found plugin dart_vlc at
/home/wildone/snap/flutter/common/flutter/.pub-cache/git/dart_vlc-349400f3978d751d45e5c4d310cd78d998742d40/
[  +14 ms] Found plugin desktop_window at
/home/wildone/snap/flutter/common/flutter/.pub-cache/git/desktop_window-56183be57bfcdf0ba8eb8ae2c2b61f687161dfa5/
[   +6 ms] Found plugin window_size at
/home/wildone/snap/flutter/common/flutter/.pub-cache/git/flutter-desktop-embedding-1d3bff412f8e93087243995570db3a56eba415e5/plu
gins/window_size/
[   +8 ms] Found plugin audio_session at
/home/wildone/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/audio_session-0.1.0/
[  +37 ms] Found plugin just_audio at
/home/wildone/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/just_audio-0.7.4/
[   +6 ms] Found plugin just_audio_web at
/home/wildone/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/just_audio_web-0.3.1/
[  +13 ms] Found plugin path_provider at
/home/wildone/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[   +4 ms] Found plugin path_provider_linux at
/home/wildone/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +4 ms] Found plugin path_provider_macos at
/home/wildone/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +6 ms] Found plugin path_provider_windows at
/home/wildone/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[ +265 ms] Found plugin dart_vlc at
/home/wildone/snap/flutter/common/flutter/.pub-cache/git/dart_vlc-349400f3978d751d45e5c4d310cd78d998742d40/
[   +3 ms] Found plugin desktop_window at
/home/wildone/snap/flutter/common/flutter/.pub-cache/git/desktop_window-56183be57bfcdf0ba8eb8ae2c2b61f687161dfa5/
[   +3 ms] Found plugin window_size at
/home/wildone/snap/flutter/common/flutter/.pub-cache/git/flutter-desktop-embedding-1d3bff412f8e93087243995570db3a56eba415e5/plu
gins/window_size/
[   +5 ms] Found plugin audio_session at
/home/wildone/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/audio_session-0.1.0/
[  +21 ms] Found plugin just_audio at
/home/wildone/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/just_audio-0.7.4/
[   +3 ms] Found plugin just_audio_web at
/home/wildone/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/just_audio_web-0.3.1/
[   +7 ms] Found plugin path_provider at
/home/wildone/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[   +3 ms] Found plugin path_provider_linux at
/home/wildone/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +2 ms] Found plugin path_provider_macos at
/home/wildone/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +4 ms] Found plugin path_provider_windows at
/home/wildone/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[  +40 ms] Generating
/home/wildone/Desktop/projects/to_do_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +232 ms] Initializing file store
[  +23 ms] Skipping target: gen_localizations
[  +13 ms] complete
[  +13 ms] Launching lib/main.dart on Linux in debug mode...
[  +13 ms] /home/wildone/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/wildone/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/wildone/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata --output-dill /tmp/flutter_tools.NZTYUY/flutter_tool.ILJWBX/app.dill
--packages /home/wildone/Desktop/projects/to_do_app/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/cache.dill.track.dill
[  +42 ms] Building Linux application...
[  +67 ms] <- compile package:to_do_app/main.dart
[   +6 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
/home/wildone/Desktop/projects/to_do_app/linux
[  +26 ms] List of devices attached
[   +7 ms] List of devices attached
[ +101 ms] CMake Error at flutter/ephemeral/.plugin_symlinks/dart_vlc/linux/CMakeLists.txt:9 (cmake_minimum_required):
[   +5 ms]   CMake 3.15 or higher is required.  You are running version 3.10.2
[   +1 ms] -- Configuring incomplete, errors occurred!
[        ] See also "/home/wildone/Desktop/projects/to_do_app/build/linux/debug/CMakeFiles/CMakeOutput.log".
[  +31 ms] Building Linux application... (completed in 232ms)
[+2125 ms] Exception: Unable to generate build files
[   +1 ms] "flutter run" took 3,623ms.
[  +10 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +186 ms] ensureAnalyticsSent: 178ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +10 ms] Shutdown hooks complete
[        ] exiting with code 1

**Comment by JustusFluegel** [comment]
please make sure you have the newest flutter version as well as the newest version of the dependencies of flutter, if you are not sure how to upgrade please try a fresh install of flutter first. 

Also in general please add version numbers and your OS/Distro into crash reports.

**Comment by k1ycee** [comment]
@JustusFluegel I am currently using flutter version 2.2.0

**Comment by JustusFluegel** [comment]
please make sure to have the newest version of cmake installed, it works for me
