### ISSUE TITLE
SetMin working on MacOS

### ISSUE THREAD

**Issue by giacomoRanieri** [mix1009/desktop_window#27]
After Updating Flutter to 2.2.2 on MacOS I receive a "MainWindow not found" message from the Future of the function "setMinWindowSize".

I'm running the application on MacOS 10.15.6

**Comment by JustusFluegel** [comment]
please add the console output and a (minimal) project to demonstrate your problem

**Comment by florianh01** [comment]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
#0      MethodChannel.binaryMessenger
package:flutter/…/services/platform_channel.dart:142
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:148
#2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:331
#3      DesktopWindow.setMinWindowSize
package:desktop_window/desktop_window.dart:25
#4      main
package:***********/main.dart:10

#5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
#6      _rootRun (dart:async/zone.dart:1354:13)
#7      _CustomZone.run (dart:async/zone.dart:1258:19)
#8      _runZoned (dart:async/zone.dart:1789:10)
#9      runZonedGuarded (dart:async/zone.dart:1777:12)
#10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
#11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
![Bildschirmfoto 2021-07-11 um 12 17 53](https://user-images.githubusercontent.com/78513002/125191387-6ed36a00-e242-11eb-800e-293851c80c83.png)

**Comment by jonorozcoc** [comment]
I'm having the same issue on Windows

**Comment by jonorozcoc** [comment]
I created a repo with a minimal project
https://github.com/jonorozcoc/flutter_desktop_issue

**Comment by LiveRock** [comment]
I am facing the same issue on Macos 11.4 Big Sur on a Mac Mini M1
