### ISSUE TITLE
Unhandled Exception: mainWindow not found

### ISSUE THREAD

**Issue by LiveRock** [mix1009/desktop_window#30]
Can't set app to full screen using the following command:

`await DesktopWindow.setFullScreen(true);`

**Error:**
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: mainWindow not found
#0      DesktopWindow.getWindowSize (package:desktop_window/desktop_window.dart:16:5)
<asynchronous suspension> 
```

What could I have done wrong?

**Comment by colatea** [comment]
I have the same problem。

`flutter: getWindowSize err: PlatformException(MAINWINDOW_NOT_FOUND, GtkWindow not found, null, null), #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      DesktopWindow.getWindowSize (package:desktop_window/desktop_window.dart:12:17)
<asynchronous suspension>
#3      FutureExtensions.onError.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
`
Environment:
OS: Manjaro Linux x86_64
Kernel: 5.10.56-1-MANJARO

**Comment by hyungtaecf** [comment]
I got the same problem with the function setMinWindowSize. It was working before, but today it was not working but not logging any error to the console. So I made a print of the result of the function and it says "mainWindow not found". I'm using MacOS.

**Comment by PhysicalRevelry** [comment]
I have the same occurrence pattern as @hyungtaecf Everything runs fine as long as I keep my computer's focus on where the desktop simulator open.

Using MacOS, Flutter 2.13, beta channel

**Comment by hi-jin** [comment]
PR #33 will help you guys.
I also forked this repo, changed code like PR did, and it works.
